### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 3d0n1** [TheDevFromKer/RemoteControl#1]
hey when i try install i get this error 

Warning: mysqli::mysqli(): (HY000/1045): Access denied for user 'magazine'@'localhost' (using password: YES) in C:\xampp\htdocs\Web-Panel\install.php on line 5
Connection failed: Access denied for user 'magazine'@'localhost' (using password: YES)

any idea what's happening here?

**Comment by TheDevFromKer** [comment]
Hello. Bad MySQL user login/password.
Remote Contol on updating. Please don`t use this now.

**Comment by 3d0n1** [comment]
> Hello. Bad MySQL user login/password.
> Remote Contol on updating. Please don`t use this now.

Okey when we can expect updates?: )
